{% set name = "spacy-universal-sentence-encoder" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spacy_universal_sentence_encoder-{{ version }}.tar.gz
  sha256: 822404c1d7c8b82ceb2385803efc11a8b3d2a08467c2083d6102a4555c82e1e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tensorflow >=2.4.0,<3.0.0
    - spacy >=3.0.0,<4.0.0
    - tensorflow-hub

test:
  imports:
    - spacy_universal_sentence_encoder
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MartinoMensio/spacy-universal-sentence-encoder
  summary: SpaCy models for using Universal Sentence Encoder from TensorFlow Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
